name: Build and Release

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Visual Studio
      uses: ilammy/msvc-dev-cmd@v1
      with:
        arch: x64
        
    - name: Install vcpkg (for dependency management)
      run: |
        git clone https://github.com/microsoft/vcpkg.git
        .\vcpkg\bootstrap-vcpkg.bat

    - name: Install MaxMindDB C library via vcpkg
      run: |
        .\vcpkg\vcpkg install libmaxminddb:x64-windows

    # Integrate vcpkg toolchain with Visual Studio and msbuild
    - name: Set VCPKG environment variables
      run: |
        echo "VCPKG_ROOT=$(pwd)/vcpkg" >> $GITHUB_ENV
        echo "VCPKG_DEFAULT_TRIPLET=x64-windows" >> $GITHUB_ENV

    - name: Build Debug DLL with vcpkg integration
      run: |
        .\vcpkg\vcpkg integrate install
        msbuild /p:Configuration=Debug /p:Platform=x64 /p:VcpkgTriplet=x64-windows /p:VcpkgEnabled=true src/libGeoLocationIIS.sln
        mkdir output/Debug
        copy /Y src\x64\Debug\libGeoLocationIIS.dll output\Debug\libGeoLocationIIS.dll

    - name: Build Release DLL with vcpkg integration
      run: |
        msbuild /p:Configuration=Release /p:Platform=x64 /p:VcpkgTriplet=x64-windows /p:VcpkgEnabled=true src/libGeoLocationIIS.sln
        mkdir output/Release
        copy /Y src\x64\Release\libGeoLocationIIS.dll output\Release\libGeoLocationIIS.dll


    - name: Zip artifacts
      run: |
        mkdir dist
        tar -cvzf dist/Debug.tar.gz -C output/Debug .
        tar -cvzf dist/Release.tar.gz -C output/Release .

    