name: Build and Release

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Visual Studio
      uses: ilammy/msvc-dev-cmd@v1
      with:
        arch: x64
        
    - name: Install vcpkg (for dependency management)
      run: |
        git clone https://github.com/microsoft/vcpkg.git
        .\vcpkg\bootstrap-vcpkg.bat

    - name: Install MaxMindDB C library via vcpkg
      run: |
        .\vcpkg\vcpkg install libmaxminddb:x64-windows

    # Integrate vcpkg toolchain with Visual Studio and msbuild
    - name: Set VCPKG environment variables
      run: |
        echo "VCPKG_ROOT=$(pwd)/vcpkg" >> $GITHUB_ENV
        echo "VCPKG_DEFAULT_TRIPLET=x64-windows" >> $GITHUB_ENV

    - name: Build Debug DLL with vcpkg integration
      run: |
        .\vcpkg\vcpkg integrate install
        msbuild /p:Configuration=Debug /p:Platform=x64 /p:VcpkgTriplet=x64-windows /p:VcpkgEnabled=true src/libGeoLocationIIS.sln
        mkdir output/Debug
        Copy-Item -Path src\x64\Debug\libGeoLocationIIS.dll -Destination output\Debug\libGeoLocationIIS.dll -Force

    - name: Build Release DLL with vcpkg integration
      run: |
        msbuild /p:Configuration=Release /p:Platform=x64 /p:VcpkgTriplet=x64-windows /p:VcpkgEnabled=true src/libGeoLocationIIS.sln
        mkdir output/Release
        Copy-Item -Path src\x64\Release\libGeoLocationIIS.dll -Destination output\Release\libGeoLocationIIS.dll -Force


    # - name: Zip artifacts
      # run: |
        # mkdir dist
        # tar -cvzf dist/Debug.tar.gz -C output/Debug .
        # tar -cvzf dist/Release.tar.gz -C output/Release .
        
    - name: Create Zipped Artifacts
      run: |
        mkdir dist
        7z a -tzip dist/Debug.zip output/Debug  # Use 7z for ZIP support on Windows
        7z a -tzip dist/Release.zip output/Release
        
    - name: Get version from git
      id: get_version
      run: echo "VERSION=$(git describe --tags --always)" >> $GITHUB_ENV

    - name: Create GitHub Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ env.VERSION }}
        release_name: Release ${{ env.VERSION }}
        draft: false
        prerelease: false

    - name: Upload Debug artifact to Release
      uses: actions/upload-release-asset@v1
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: dist/Debug.tar.gz
        asset_name: libGeoLocationIIS-Debug-${{ env.VERSION }}.tar.gz
        asset_content_type: application/gzip

    - name: Upload Release artifact to Release
      uses: actions/upload-release-asset@v1
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: dist/Release.tar.gz
        asset_name: libGeoLocationIIS-Release-${{ env.VERSION }}.tar.gz
        asset_content_type: application/gzip
    